name: Push Events 
on:
  push:
    branches:
        - main
        - test
jobs:
    show-info:
        runs-on: ubuntu-latest
        steps:
            - name: Info
              run: |
                echo "This is a push event on all the branches"
              if: github.ref == 'refs/heads/main' && github.event_name == 'push'
            - name: Info1
              run: |
                echo "This is a push event on all the branches"
              if: github.ref == 'refs/heads/main' && github.event_name == 'push'