name: Data Passing Workflow
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'         # Any markdown file (README.md, docs/*.md, etc.)
      - 'docs/**'       # A docs directory, if you have one
      - '.gitignore'    # Often useful to ignore too
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Data
        run: echo "Some data generated in job1 by bala @ `date` " >> data.txt
      - name: Upload data as artifactor
        uses: actions/upload-artifact@v4
        with:
          name: data-artifact
          path: data.txt
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Download data artifacts
        uses: actions/download-artifact@v5
        with:
          name: data-artifact
          path: data/
      - name: Use data in job2
        run: cat data/data.txt

