name: Karthikeyan
on:
  push:
jobs:
  initial:
    runs-on: ubuntu-latest
      jobs:
        - name: test
          run: echo "This is test"
        - name: test1
          run: echo "This is second test"
