name: Manual Workflow 
on:
 workflow_dispatch:
jobs:
    run_manual_tasks:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 
              uses: actions/checkout@v4
            - name: Info
              run: |
                echo "This is a manual workflow event on all the branches"