server:
  port: 8080
  servlet:
    context-path: /auth

spring:
  application:
    name: auth-api

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
