apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multipod
  name: multipod
spec:
  volumes:
    - name: test-vol
      emptyDir: {}
  containers:
  - image: nginx
    name: nginxpod
    volumeMounts:
      - name: test-vol
        mountPath: /var/log/nginx
  - image: busybox
    name: busypod
    command: ["sh", "-c", "sleep 1h" ]
    volumeMounts:
      - name: test-vol
        mountPath: /data/nginx-log

