name: Simple_Workflow
on:
  push:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: first
        run: echo "First Step"
      - name: second
        run: echo "Second Step"
      - name: third
        run: echo "Third step" 
