name: Simple_Workflow
on:
  push:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: first
        runs: echo "First Step"
      - name: second
        runs: echo "Second Step"
      - name: third
        runs: echo "Third step" 
