name: my first workflow
on: push
jobs:
    jobs-1:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1
              run: echo "Hello from Step 1"
            - name: Step 2
              run: echo "Hello from Step 2"
    jobs-2:
        runs-on: ubuntu-latest
        steps:
            - name: Final Step
              run: echo "Hello from final step"
            - name: another Step
              run: echo "Hello from another step"