name: MyFirstWorkflow
on:
    push
jobs:
    runs-on: ubuntu-latest
    job1:
        - name: My First Step
          run: echo "My first step"
        - name: My Second step
          run: echo "My Second step"
