name: MyFirstWorkflow
on:
    push:
jobs:
    job1:
        runs-on: ubuntu-latest
        steps: 
            - name: My First Step
              run: echo "My first step"
            - name: My Second step
              run: Echo "My Second step"
