name: FirstWorkFlow
on:
  workflow_dispatch:
jobs:
  initial:
    runs-on: ubuntu-latest
    steps:
      - name: first
        run: echo "First"
      - name: second
        run: echo "Second"
  middle:
    runs-on: ubuntu-latest
    steps:
      - name: third 
        run: echo "Third"
      - name: fourth
        run: echo "Fourth"
